service: anvidpoketcg

frameworkVersion: ">=4.0.0"

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    PRODUCTS_TABLE: ${self:service}-products-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}/index/*

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node22

plugins:
  - serverless-offline

functions: ${file(resources/functions.yml)}

resources:
  - ${file(resources/dynamodb.yml)}